### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by Bazmundi** [DesignEngrLab/fmdtools#7]
I notice you have user modelling in your approach.

Have you considered using tool such as [cogulator](http://cogulator.io/index.html) in parallel to capture the analysis if users and then perhaps parse cogulator files into your human component representation?

**Comment by hulsed** [comment]
This project has extremely limited resources and is not presently writing any extensions/integrations for preexisting modelling languages. As a matter of design philosophy, for a research code like this I recommend not having domain specific languages and just using Python instead--it lets you express more without worrying about whether your intent is being translated into the simulation correctly. However, I don't see a major technical barrier to doing that and if this is a desired use-case, I welcome any contributions.
